# Generated by Django 2.1.5 on 2019-02-09 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockoverflow', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='register',
        ),
        migrations.DeleteModel(
            name='soaccount',
        ),
        migrations.AddField(
            model_name='questions',
            name='Question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockoverflow.user'),
        ),
        migrations.AddField(
            model_name='questions',
            name='ans',
            field=models.ManyToManyField(to='stockoverflow.Answers'),
        ),
        migrations.AddField(
            model_name='answers',
            name='ans_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockoverflow.user'),
        ),
    ]
